version: "3"
services:
  strapi:
    container_name: strapi
    build: ./strapi-app/
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
    volumes:
      - ./strapi-app/config:/opt/app/config
      - ./strapi-app/src:/opt/app/src
      - ./strapi-app/package.json:/opt/package.json
      - ./strapi-app/yarn.lock:/opt/yarn.lock
      - ./strapi-app/.env:/opt/app/.env
      - ./strapi-app/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
      - strapi-db-data:/usr/src/app/data

    ports:
      - "5432:5432"
    networks:
      - strapi

  front-end:
    build:
      context: ./opsci-strapi-frontend/
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file: ./strapi-app/.env
    depends_on:
      - strapi
    volumes:
      - strapi-db-data:/usr/src/app/data
    networks:
      - strapi

volumes:
  strapi-data:
  strapi-db-data:

networks:
  strapi:
    driver: bridge
